# -*- coding: utf-8 -*-
"""Lista_EP_EstatísticaDescritiva

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HHEX9klZDex91oeSwc7AEdZ-gSrIwTf8

Questão 1
"""

import csv

with open('/content/drive/MyDrive/StudentsPerformance - StudentsPerformance.csv') as arquivo_csv:
  leitor_csv = csv.DictReader(arquivo_csv)
  total = 0 
  female = 0 
  male = 0 

  for linha in leitor_csv:
    if(linha['gender'] == 'female'):
      female += 1
    elif(linha['gender'] == 'male'):
      male +=1

    total+=1

print(f' Total Observado: {total}\n',f'Frequência Gender Female: {female}\n',
      f'Frequência Gender Male: {male}\n',
      f'Frequência Relativa Gender Female: {(female*100)/total}%\n',
      f'Frequência Relativa Gender Male:  {(male*100)/total}%')

"""Questão 2"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/StudentsPerformance - StudentsPerformance.csv') 
#Carrega um arquivo CSV em um DataFrame do pandas, com o caminho do arquivo

# Média
med = df['math score'].mean()
# Moda
moda = df['math score'].mode()[0]  # se houver várias modas, retorna a primeira
# Mediana
mediana = df['math score'].median()
# Valor máximo
val_max = df['math score'].max()
# Valor mínimo
val_min = df['math score'].min()
# Amplitude
amplitude = val_max - val_min
# Variação
variac = df['math score'].var().round(3)
# Desvio padrão
desv_padrao = df['math score'].std().round(3)
# Quartis
q1 = df['math score'].quantile(0.25)
q2 = df['math score'].quantile(0.5)
q3 = df['math score'].quantile(0.75)

print('Valores referentes a coluna Math Score:')
print("a) Valor mínimo:", val_min)
print("b) Média:", med)
print("c) Mediana:", mediana)
print("d) Moda:", moda)
print("e) Amplitude:", amplitude)
print("f) Variância:", variac)
print("g) Desvio padrão:", desv_padrao)
print("h) Valor máximo:", val_max)
print("i) Quartil 1:", q1)
print("j) Quartil 2:", q2)
print("k) Quartil 3:", q3)

"""Questão 3"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/StudentsPerformance - StudentsPerformance.csv')

# Média
med = df['reading score'].mean()
# Moda
moda = df['reading score'].mode()[0]  # se houver várias modas, retorna a primeira
# Mediana
mediana = df['reading score'].median()
# Valor máximo
val_max = df['reading score'].max()
# Valor mínimo
val_min = df['reading score'].min()
# Amplitude
amplitude = val_max - val_min
# Variação
variac = df['reading score'].var().round(3)
# Desvio padrão
desv_padrao = df['reading score'].std().round(3)
# Quartis
q1 = df['reading score'].quantile(0.25)
q2 = df['reading score'].quantile(0.5)
q3 = df['reading score'].quantile(0.75)

print('Valores referentes a coluna Reading Score:')
print("a) Valor mínimo:", val_min)
print("b) Média:", med)
print("c) Mediana:", mediana)
print("d) Moda:", moda)
print("e) Amplitude:", amplitude)
print("f) Variância:", variac)
print("g) Desvio padrão:", desv_padrao)
print("h) Valor máximo:", val_max)
print("i) Quartil 1:", q1)
print("j) Quartil 2:", q2)
print("k) Quartil 3:", q3)

"""Questão 4"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/StudentsPerformance - StudentsPerformance.csv')

# Média
med = df['writing score'].mean()
# Moda
moda = df['writing score'].mode()[0]  # se houver várias modas, retorna a primeira
# Mediana
mediana = df['writing score'].median()
# Valor máximo
val_max = df['writing score'].max()
# Valor mínimo
val_min = df['writing score'].min()
# Amplitude
amplitude = val_max - val_min
# Variação
variac = df['writing score'].var().round(3)
# Desvio padrão
desv_padrao = df['writing score'].std().round(3)
# Quartis
q1 = df['writing score'].quantile(0.25)
q2 = df['writing score'].quantile(0.5)
q3 = df['writing score'].quantile(0.75)

print('Valores referentes a coluna Writing Score:')
print("a) Valor mínimo:", val_min)
print("b) Média:", med)
print("c) Mediana:", mediana)
print("d) Moda:", moda)
print("e) Amplitude:", amplitude)
print("f) Variância:", variac)
print("g) Desvio padrão:", desv_padrao)
print("h) Valor máximo:", val_max)
print("i) Quartil 1:", q1)
print("j) Quartil 2:", q2)
print("k) Quartil 3:", q3)

"""Questão 5

"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/StudentsPerformance - StudentsPerformance.csv')

med_fem = df[df['gender'] == 'female']['math score'].mean()
med_masc = df[df['gender'] == 'male']['math score'].mean()

print('O sexo que obteve o melhor desempenho nos testes de matemática foi o:')
if med_fem > med_masc:
    print('Feminino')
else:
    print('Masculino')

"""Questão 6

"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/StudentsPerformance - StudentsPerformance.csv')

med_fem = df[df['gender'] == 'female']['reading score'].mean()
med_masc = df[df['gender'] == 'male']['reading score'].mean()

print('O sexo que obteve o melhor desempenho nos testes de leitura foi o:')
if med_fem > med_masc:
    print('Feminino')
else:
    print('Masculino')

"""Questão 7"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/StudentsPerformance - StudentsPerformance.csv')

med_fem = df[df['gender'] == 'female']['writing score'].mean()
med_masc = df[df['gender'] == 'male']['writing score'].mean()

print('O sexo que obteve o melhor desempenho nos testes de escrita foi o:')
if med_fem > med_masc:
    print('Feminino')
else:
    print('Masculino')

"""Questão 8"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/StudentsPerformance - StudentsPerformance.csv')

percentil_25_math = df['math score'].quantile(0.25)
percentil_25_reading = df['reading score'].quantile(0.25)
percentil_25_writing = df['writing score'].quantile(0.25)

print('--- As respostas certas são ----')
# verificar as afirmações
if percentil_25_math <= 57:
    print("a) 25% dos(as) estudantes obtêm 'score' igual ou menor a 57 pontos em matemática.")

if percentil_25_reading <= 57:
    print("b) 25% dos(as) estudantes obtêm 'score' igual ou menor a 57 pontos em leitura.")

if percentil_25_writing <= 57:
    print("c) 25% dos(as) estudantes obtêm 'score' igual ou menor a 57 pontos em escrita.")

if percentil_25_math <= 59:
    print("d) 25% dos(as) estudantes obtêm 'score' igual ou menor a 59 pontos em matemática.")

if percentil_25_reading <= 59:
    print("e) 25% dos(as) estudantes obtêm 'score' igual ou menor a 59 pontos em leitura.")

if percentil_25_writing <= 59:
    print("f) 25% dos(as) estudantes obtêm 'score' igual ou menor a 59 pontos em escrita.")

if percentil_25_math <= 57.75:
    print("g) 25% dos(as) estudantes obtêm 'score' igual ou menor a 57.75 pontos em matemática.")

if percentil_25_reading <= 57.75:
    print("h) 25% dos(as) estudantes obtêm 'score' igual ou menor a 57.75 pontos em leitura.")

if percentil_25_writing <= 57.75:
    print("i) 25% dos(as) estudantes obtêm 'score' igual ou menor a 57.75 pontos em escrita.")

if df['math score'].quantile(0.75) >= 77:
    print("j) Somente 25% dos(as) estudantes obtêm 'score' igual ou superior a 77 pontos em matemática.")

if df['writing score'].quantile(0.75) >= 77:
    print("k) Somente 25% dos(as) estudantes obtêm 'score' igual ou superior a 77 pontos em escrita.")

if df['math score'].quantile(0.75) >= 79:
    print("l) Somente 25% dos(as) estudantes obtêm 'score' igual ou superior a 79 pontos em matemática.")

if df['reading score'].quantile(0.75) >= 79:
    print("m) Somente 25% dos(as) estudantes obtêm 'score' igual ou superior a 79 pontos em leitura.")

if df['writing score'].quantile(0.75) >= 79:
    print("n) Somente 25% dos(as) estudantes obtêm 'score' igual ou superior a 79 pontos em escrita.")

"""Questão 9 

"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/StudentsPerformance - StudentsPerformance.csv')

#calcula a média e o desvio padrão para cada disciplina e, em seguida, 
#usa esses valores para calcular os limites dos intervalos 
#usando a regra empírica.

import pandas as pd

# calcular a média e o desvio padrão para cada disciplina
media_math = df['math score'].mean()
std_math = df['math score'].std()

media_reading = df['reading score'].mean()
std_reading = df['reading score'].std()

media_writing = df['writing score'].mean()
std_writing = df['writing score'].std()

# calcular os limites dos intervalos usando a regra empírica
#cerca de 95% dos dados estão a uma distância de dois desvios padrão da média
math_lower = round(media_math - 2*std_math, 3)
math_upper = round(media_math + 2*std_math, 3)

reading_lower = round(media_reading - 2*std_reading, 3)
reading_upper = round(media_reading + 2*std_reading, 3)

writing_lower = round(media_writing - 2*std_writing, 3)
writing_upper = round(media_writing + 2*std_writing, 3)

# imprimir os resultados
print("De acordo com a regra empírica, podemos estimar que:")
print("95% dos estudantes obtêm nota no intervalo [{}, {}] em matemática".format(math_lower, math_upper))
print("95% dos estudantes obtêm nota no intervalo [{}, {}] em leitura".format(reading_lower, reading_upper))
print("95% dos estudantes obtêm nota no intervalo [{}, {}] em escrita".format(writing_lower, writing_upper))